Repository Shreyaa173/Code-Book, pull requests merged in 2024-10, with the labels that each got.

#60 Added a Responsive design to course section and added youtube channels links to the cards
  src/App.css
  src/components/CourseCards.jsx
  style.css
Labels: gssoc-extd, hacktoberfest-accepted, level-2

#228 Added Email functionalty to the contact form issue #128
  server/.gitignore
  server/controllers/controller.js
  server/package-lock.json
  server/package.json
  server/routes/Emailroutes.js
  server/server.js
  src/components/Contact.jsx
Labels: gssoc-ext, level2

#253 chatbot added ✨
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#337 Changed Component style to match the website theme.
  src/App.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#415 Bug/improve course cards layout
  src/App.jsx
  src/components/Card.jsx
  src/components/CourseCards.jsx
  src/components/Courses.jsx
  src/components/Faqs.css
  src/components/Faqs.jsx
  src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#367 Added Google OAuth
  backend/.env
  package-lock.json
  package.json
  src/components/Login.css
  src/components/Login.jsx
  src/components/Signup.css
  src/components/Signup.jsx
  src/firebase/auth.js
  src/firebase/firebase.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#433 added reset passwprd functionality
  backend/controllers/auth.js
  backend/package-lock.json
  backend/package.json
  package-lock.json
  src/App.jsx
  src/components/Login.css
  src/components/Login.jsx
  src/components/Resetpassword.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#435 Update Profile backend
  backend/controllers/auth.js
  backend/models/Profile.js
  backend/models/User.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#445 Custom: Adding pdf links in courses
  src/App.css
  src/components/Card.jsx
  src/components/CourseCards.jsx
  src/components/Introduction.jsx
  src/components/Slideshow.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2
